POST http://localhost:3000/clubs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZmODE0M2MyLWY2ODAtNDkyZS1iMGE4LWJiNjU0NDJlMGEzOCIsInVzZXJuYW1lIjoidGVzdFVzZXIiLCJpYXQiOjE3NjE4NTcwMDYsImV4cCI6MTc2MTk0MzQwNn0._XAxwgbm-7MSpWOdTYP43VBGDTsTNo7sZc6bkv4nmQU

{
    "title": "@nd"
}