DELETE http://localhost:3000/clubs/04fa526c-8d18-468a-9935-00a048575c0e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZmODE0M2MyLWY2ODAtNDkyZS1iMGE4LWJiNjU0NDJlMGEzOCIsInVzZXJuYW1lIjoidGVzdFVzZXIiLCJpYXQiOjE3NjE4NTcwMDYsImV4cCI6MTc2MTk0MzQwNn0._XAxwgbm-7MSpWOdTYP43VBGDTsTNo7sZc6bkv4nmQU
