GET http://localhost:3000/clubs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA0NTIzMTNjLWE4MTctNDY2Yi1hMjVjLWE5ZTUyNDVmMmYzOSIsInVzZXJuYW1lIjoiSm9obiIsImlhdCI6MTc2MjMyNDQ1MSwiZXhwIjoxNzYyNDEwODUxfQ.7d3EESK_s-Z3mOpJSWliYbSgBOV0qRABmKZ23pDht9s